/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.max;

public class Maximum {
	public static void main(String[] args) {
		System.out.println("Welcome to world of max ");
	}
}
