/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.max;

public class Maximum <E extends Comparable<E>> {
	E a, b, c ;
	Maximum(E a,E b, E c) {
		this.a = a;
		this.b = b;
		this.c = c;
	}
	public static void main(String[] args) {
		System.out.println("Welcome to world of max ");
		
	}
	
	public static <E extends Comparable<E>> E maximum(E a ,E b ,E c) {
		E max = a;
		if(b.compareTo(max)>0)
			max=b;
		if(c.compareTo(max)>0)
			max=c;
		
		return max;
	}
	
}
