/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.max;

import org.junit.Test;

import com.cp.max.Maximum;

import static org.junit.Assert.*;

public class TestMaximum {
    
	
}
