/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.max;

import org.junit.Test;

import com.cp.max.Maximum;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Assert;

public class TestMaximum {
    
	@Test
	public void testIntMaximum() {
		ArrayList<Integer> l = new ArrayList<>();
		l.add(1);
		l.add(2);
		l.add(3);
		l.add(4);
		Assert.assertEquals((Integer)4, Maximum.maximum(l));
	}

	@Test
	public void testFloatMaximum() {
		ArrayList<Float> l = new ArrayList<>();
		l.add(1.1f);
		l.add(2.2f);
		l.add(3.3f);
		l.add(4.4f);
		l.add(5.5f);
		Assert.assertEquals((Float)5.5f, Maximum.maximum(l));
	}

	@Test
	public void testStringMaximum() {
		ArrayList<String> l = new ArrayList<>();
		l.add("cat");
		l.add("dog");
		l.add("bull");
		l.add("elephant");
		l.add("zebra");
		Assert.assertEquals("zebra", Maximum.maximum(l));
	}

}
